// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace University.Models
{
    public partial class PrepDisciplini
    {
        public int Id { get; set; }
        public int? PrepId { get; set; }
        public int? DiscId { get; set; }

        public virtual Disciplini Disc { get; set; }
        public virtual Prepodavateli Prep { get; set; }
    }
}