// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace University.Models
{
    public partial class Disciplini
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool? Deleted { get; set; }
    }
}