// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace University.Models
{
    public partial class Prepodavateli
    {
        public Prepodavateli()
        {
            Kafedris = new HashSet<Kafedri>();
        }

        public int Id { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int? Stepen { get; set; }
        public int? Dolznost { get; set; }
        public int Nagruzka { get; set; }
        public int Kafedra { get; set; }

        public virtual Dolznosti DolznostNavigation { get; set; }
        public virtual Kafedri KafedraNavigation { get; set; }
        public virtual Stepeni StepenNavigation { get; set; }
        public virtual ICollection<Kafedri> Kafedris { get; set; }
    }
}